services:
  - type: web
    name: mc-adarkwah
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://mc-adarkwah.onrender.com
      - key: CONTACT_EMAIL
        value: mcadarkwah@gmail.com
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: mubarakamui776@gmail.com
